/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminInstagramLiveIndexRouteImport } from './routes/admin/instagram-live/index'
import { Route as AdminInstagramLiveNewRouteImport } from './routes/admin/instagram-live/new'
import { Route as AdminInstagramLiveIdRouteImport } from './routes/admin/instagram-live/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstagramLiveIndexRoute = AdminInstagramLiveIndexRouteImport.update({
  id: '/instagram-live/',
  path: '/instagram-live/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstagramLiveNewRoute = AdminInstagramLiveNewRouteImport.update({
  id: '/instagram-live/new',
  path: '/instagram-live/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstagramLiveIdRoute = AdminInstagramLiveIdRouteImport.update({
  id: '/instagram-live/$id',
  path: '/instagram-live/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/instagram-live/$id': typeof AdminInstagramLiveIdRoute
  '/admin/instagram-live/new': typeof AdminInstagramLiveNewRoute
  '/admin/instagram-live/': typeof AdminInstagramLiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/instagram-live/$id': typeof AdminInstagramLiveIdRoute
  '/admin/instagram-live/new': typeof AdminInstagramLiveNewRoute
  '/admin/instagram-live': typeof AdminInstagramLiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/instagram-live/$id': typeof AdminInstagramLiveIdRoute
  '/admin/instagram-live/new': typeof AdminInstagramLiveNewRoute
  '/admin/instagram-live/': typeof AdminInstagramLiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/admin/instagram-live/$id'
    | '/admin/instagram-live/new'
    | '/admin/instagram-live/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/instagram-live/$id'
    | '/admin/instagram-live/new'
    | '/admin/instagram-live'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/admin/instagram-live/$id'
    | '/admin/instagram-live/new'
    | '/admin/instagram-live/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instagram-live/': {
      id: '/admin/instagram-live/'
      path: '/instagram-live'
      fullPath: '/admin/instagram-live/'
      preLoaderRoute: typeof AdminInstagramLiveIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instagram-live/new': {
      id: '/admin/instagram-live/new'
      path: '/instagram-live/new'
      fullPath: '/admin/instagram-live/new'
      preLoaderRoute: typeof AdminInstagramLiveNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instagram-live/$id': {
      id: '/admin/instagram-live/$id'
      path: '/instagram-live/$id'
      fullPath: '/admin/instagram-live/$id'
      preLoaderRoute: typeof AdminInstagramLiveIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInstagramLiveIdRoute: typeof AdminInstagramLiveIdRoute
  AdminInstagramLiveNewRoute: typeof AdminInstagramLiveNewRoute
  AdminInstagramLiveIndexRoute: typeof AdminInstagramLiveIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminInstagramLiveIdRoute: AdminInstagramLiveIdRoute,
  AdminInstagramLiveNewRoute: AdminInstagramLiveNewRoute,
  AdminInstagramLiveIndexRoute: AdminInstagramLiveIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
